name: Update Dependencies

concurrency: deps-${{ github.ref }}

on:
    workflow_dispatch:
    schedule:
        - cron: "0 2 * * 0"
    repository_dispatch:
        types:
            - common-published
            - db-published

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version-file: go.mod
            - name: Update dependencies
              run: |
                    git config --global user.email "ci@sweetrpg.com"
                    git config --global user.name "SweetRPG Dependency Updater"
                    git checkout ${{ github.head_ref || github.ref_name }}

                    go get -u ./...
                    go mod tidy

                    git add go.mod go.sum
                    git commit -m "Update dependencies" || exit 0
                    git push origin || exit 0
