name: Pull Request

on:
    pull_request:
        branches: [python]
        paths:
            - "src/**"
            - "tests/**"
            - setup.cfg
            - setup.py
            - tox.ini
            - "requirements/*.txt"
            - "docs/**"

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: linux,
                          python: "3.11",
                          os: ubuntu-latest,
                          tox: py311,
                      }
                    # - {
                    #       name: Windows,
                    #       python: "3.9",
                    #       os: windows-latest,
                    #       tox: py310,
                    #   }
                    # - { name: Mac, python: "3.9", os: macos-latest, tox: py310 }
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: update-pip
              run: |
                  pip install -U wheel
                  pip install -U setuptools
                  python -m pip install -U pip
            - name: get-pip-cache-dir
              id: pip-cache
              run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
            - name: cache-pip
              uses: actions/cache@v2
              with:
                  path: ${{ steps.pip-cache.outputs.dir }}
                  key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('setup.py') }}|${{ hashFiles('requirements/*.txt') }}
            - name: install-utils
              run: pip install tox
            # - name: lint
            #   run: black --check -t py310 --diff --color src
            - name: tests
              run: tox -e ${{ matrix.tox }}
