name: pr

on:
    pull_request:
        branches: [rust]
        paths:
            - "src/**"
            - "tests/**"
            - "benches/**"
            - "examples/**"

env:
    CARGO_TERM_COLOR: always

jobs:
    tests:
        name: linux
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                toolchain:
                    - stable
                    - beta
                    - nightly
        steps:
            - uses: actions/checkout@v3
            - name: install-toolchain
              run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - name: build
              run: cargo build --verbose
            - name: lint
              run: cargo check --verbose
            - name: tests
              run: cargo test --verbose
            - name: coverage
              uses: paambaati/codeclimate-action@v5.0.0
              env:
                CC_TEST_REPORTER_ID: 7b6f344f23d6c8daa4dea785e0cd44d1b70914efb24cb7fe364356f014e88526
